In [1]:
print('Convolution Basic')

Convolution Basic


### Convolution: 1D operation with Python (Numpy/Scipy)

In [0]:
import numpy as np


## There are three methods to apply kernel on the matrix :

1. With Padding(full)
2. With Padding(same)
3. Without Padding(valid)

In [0]:
#Definig the image and kernel 


h = [3,8,5,3,2] # Image
x = [2,6,7] # Kernel

In [9]:
# Convolution Operation With Padding (full)

y = np.convolve(x,h) # default value is full (or) we can even specify 'full'
print(y)

[ 6 34 79 92 57 33 14]


In [10]:
# Convolution Operation With Padding (Same)
y2 = np.convolve(x,h,'same')
y2

array([34, 79, 92, 57, 33])

In [11]:
y3 = np.convolve(x, h ,'valid')
y3

array([79, 92, 57])

### Convolution: 2D operation with Python (Numpy/Scipy)

In [0]:
# Defining Sample Image and Kernel

I = [[2,3,4],
     [6,4,2],
     [9,6,7],] # Image

k =[[-1, 2]] # Kernel    

In [19]:
# Convolution Operation (full)
from scipy import signal as sg

y1 = sg.convolve(I, k, 'full')
y1 

array([[-2,  1,  2,  8],
       [-6,  8,  6,  4],
       [-9, 12,  5, 14]])

In [20]:
y2 = sg.convolve(I, k, 'same')
y2

array([[-2,  1,  2],
       [-6,  8,  6],
       [-9, 12,  5]])

In [21]:
y3 = sg.convolve(I, k, 'valid')
y3

array([[ 1,  2],
       [ 8,  6],
       [12,  5]])

In [25]:
I= [[255,   7,  3],
    [212, 240,  4],
    [218, 216, 230],] # Image

g= [[-1,  1],
    [ 2,  3],]   # Kernel

y1 = sg.convolve(I, g, mode='full')
print(y1)
print()
y2 = sg.convolve(I, g, mode='same')
print(y2)
print()
y3 = sg.convolve(I, g, mode = 'valid')
print(y3)

[[-255  248    4    3]
 [ 298  751  263   13]
 [ 206 1118  714  242]
 [ 436 1086 1108  690]]

[[-255  248    4]
 [ 298  751  263]
 [ 206 1118  714]]

[[ 751  263]
 [1118  714]]


### Coding with TensorFlow

The output size without zero padding 'VALID' mode:

* input size - kernel dimension + 1

In [26]:
import tensorflow as tf

Suppose that you have two tensors:

* 3x3 filter (4D tensor = [3,3,1,1] = [width, height, channels, number of filters])
* 10x10 image (4D tensor = [1,10,10,1] = [batch size, width, height, number of channels]

In [0]:
input = tf.Variable(tf.random_normal([1,10,10,1]))

In [0]:
filter = tf.Variable(tf.random_normal([3,3,1,1]))

In [0]:
op = tf.nn.conv2d(input, filter , strides =[1,1,1,1], padding='VALID')
op2 = tf.nn.conv2d(input, filter, strides=[1,1,1,1], padding='SAME')

In [31]:
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)

  print(input.eval())
  print('\n')
  print(filter.eval())
  print('\n')
  print(sess.run(op))
  print('\n')
  print(sess.run(op2))

[[[[ 0.24288796]
   [-1.1904343 ]
   [-1.2991123 ]
   [-0.17651491]
   [ 1.2897655 ]
   [-0.38934058]
   [-1.6995641 ]
   [-0.84308285]
   [ 0.5754869 ]
   [-0.33533153]]

  [[-0.47177422]
   [-0.8591989 ]
   [ 0.06257936]
   [-0.53170717]
   [ 0.20754379]
   [-0.5724353 ]
   [-0.3309563 ]
   [-0.917383  ]
   [ 1.3625333 ]
   [ 0.20768575]]

  [[ 0.7184819 ]
   [-0.7505    ]
   [-0.11589186]
   [-2.2060738 ]
   [ 1.882827  ]
   [ 2.389995  ]
   [-0.88361835]
   [ 0.6666137 ]
   [-0.20240413]
   [ 0.39616853]]

  [[ 1.5364176 ]
   [-0.25411245]
   [ 0.17745541]
   [-0.5729985 ]
   [-1.6137792 ]
   [-0.2603571 ]
   [ 1.4064711 ]
   [ 2.4799223 ]
   [ 1.0263125 ]
   [-0.8117784 ]]

  [[ 0.6541823 ]
   [ 0.68655807]
   [ 0.76741415]
   [-2.961327  ]
   [-0.06303049]
   [-0.5617649 ]
   [ 0.8706512 ]
   [ 1.3880113 ]
   [-0.5006021 ]
   [-0.06440057]]

  [[-0.25702056]
   [ 0.09459096]
   [ 0.534621  ]
   [-0.7391786 ]
   [-0.59508127]
   [-0.23842175]
   [ 0.8545358 ]
   [-0.00878896]
   [