<a href="https://colab.research.google.com/github/Prajwal270/Tensorflow-Implementation/blob/master/Logistic_regression_with_TF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [86]:
print('Logistic Regression with TensorFlow')

Logistic Regression with TensorFlow


We are going to use famous iris dataset. Importing it from sklearn.dataset 

In [0]:
# Importing required libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [0]:
import tensorflow as tf
from sklearn.model_selection import train_test_split

Getting the data.

In [0]:
from sklearn.datasets import load_iris

In [0]:
iris = load_iris()

In [0]:
iris_X, iris_y = iris.data[:-1,:], iris.target[:-1]
iris_y= pd.get_dummies(iris_y).values

In [0]:
train_x, test_x, train_y, test_y = train_test_split(iris_X, iris_y, test_size = 0.3, random_state = 12)

In [93]:
train_x

array([[5.4, 3.7, 1.5, 0.2],
       [5.1, 3.8, 1.6, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [6.7, 3.3, 5.7, 2.1],
       [5. , 3.4, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [6. , 3.4, 4.5, 1.6],
       [6.9, 3.1, 4.9, 1.5],
       [6.1, 2.9, 4.7, 1.4],
       [5.3, 3.7, 1.5, 0.2],
       [6.4, 2.7, 5.3, 1.9],
       [5.8, 2.6, 4. , 1.2],
       [6.1, 3. , 4.6, 1.4],
       [6.9, 3.2, 5.7, 2.3],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.5, 5. , 2. ],
       [5.4, 3.9, 1.7, 0.4],
       [6.8, 3.2, 5.9, 2.3],
       [4.9, 2.5, 4.5, 1.7],
       [5.8, 2.8, 5.1, 2.4],
       [6. , 3. , 4.8, 1.8],
       [6.7, 3.1, 4.7, 1.5],
       [4.9, 2.4, 3.3, 1. ],
       [5. , 2.3, 3.3, 1. ],
       [6. , 2.7, 5.1, 1.6],
       [7.6, 3. , 6.6, 2.1],
       [5.1, 3.5, 1.4, 0.2],
       [6.7, 3.1, 5.6, 2.4],
       [7.9, 3.8, 6.4, 2. ],
       [4.9, 3.1, 1.5, 0.2],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3.8, 1.7, 0.3],
       [6.4, 3.2, 5.3, 2.3],
       [7.7, 2.8, 6.7, 2. ],
       [5. , 3

In [94]:
train_x.shape

(104, 4)

In [95]:
train_x.dtype

dtype('float64')

In [0]:
train_x = train_x.astype('float32')
test_x = test_x.astype('float32')

In [128]:
train_x.dtype

dtype('float32')

In [130]:
test_x.dtype

dtype('float32')

In [131]:
train_y.dtype

dtype('uint8')

In [132]:
test_x

array([[5. , 3.5, 1.3, 0.3],
       [6.7, 3. , 5.2, 2.3],
       [4.4, 3. , 1.3, 0.2],
       [5.7, 2.8, 4.1, 1.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.5, 3. , 5.5, 1.8],
       [6.5, 3. , 5.2, 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [5.1, 3.3, 1.7, 0.5],
       [5.6, 3. , 4.5, 1.5],
       [5.4, 3.9, 1.3, 0.4],
       [5.4, 3.4, 1.5, 0.4],
       [5.1, 3.7, 1.5, 0.4],
       [7. , 3.2, 4.7, 1.4],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [5.9, 3. , 4.2, 1.5],
       [4.6, 3.4, 1.4, 0.3],
       [6.3, 2.5, 4.9, 1.5],
       [4.9, 3. , 1.4, 0.2],
       [6.1, 2.8, 4. , 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5. , 1.7],
       [5.5, 2.6, 4.4, 1.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [5.1, 3.5, 1.4, 0.3],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [5.5, 4.2, 1.4, 0.2],
       [5.8, 2

In [133]:
train_y[0:10]

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0]], dtype=uint8)

In [134]:
train_y.shape

(104, 3)

In [135]:
test_y.shape

(45, 3)

Our Logistic Regression simple equation :   Yhat = sigmodi( W * X + b)

In [0]:
#a = tf.matmul( X, weight , name = 'a')
#b = tf.add(a,bias, name = 'b')
#Yhat = tf.nn.sigmoid(b, name = 'Yhat')

In [0]:
num_features = train_x.shape[1]
num_labels = train_y.shape[1]

In [138]:
print(num_features)
print(num_labels)

4
3


If we go on a simple way of making model i.e. just by building the equation and then training it.

In [0]:
w = tf.Variable(tf.zeros([num_features,num_labels], dtype ='float32') )
b = tf.Variable(tf.zeros([1, num_labels], dtype='float32'))


In [142]:
print(w.dtype)

<dtype: 'float32_ref'>


In [143]:
print(b.dtype)

<dtype: 'float32_ref'>


In [144]:
print(w.shape)
print(b.shape)

(4, 3)
(1, 3)


In [0]:
a = tf.matmul(train_x, w, name='a')

In [146]:
a

<tf.Tensor 'a_3:0' shape=(104, 3) dtype=float32>

In [147]:
a.shape

TensorShape([Dimension(104), Dimension(3)])

In [148]:
print(a)

Tensor("a_3:0", shape=(104, 3), dtype=float32)


In [0]:
b = tf.add(a, b ,name = 'b')

In [150]:
print(b.shape)

(104, 3)


In [0]:
yhat = tf.nn.sigmoid(b, name = 'yhat')

In [152]:
yhat

<tf.Tensor 'yhat_2:0' shape=(104, 3) dtype=float32>

In [153]:
yhat.shape

TensorShape([Dimension(104), Dimension(3)])

In [154]:
# if we want to some of the calculated values
init_op = tf.global_variables_initializer()
s = tf.Session()
s.run(init_op)
s.run(yhat[0:10])

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]], dtype=float32)

In [155]:
s.run(a[0:10])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [156]:
s.run(b[0:10])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [0]:
# We need to close the session
s.close()

In [0]:
# now define the loss function 
loss = tf.reduce_mean(tf.square(yhat - train_y))

In [0]:
optimizer = tf.train.GradientDescentOptimizer(0.01)

In [0]:
train = optimizer.minimize(loss)

In [0]:
# Now to train the model we need to define a session and initialize all the variables and invoke a for loop

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [0]:
loss = []
t = []
for step in range(100):
    a, b, c , d = sess.run([train, loss , w, b])
    loss.append(b)
    if step % 5 ==0: 
        print(a, b , c ,d)
        t.append([c,d])

None [] [[-0.03999541 -0.02521073 -0.0164295 ]
 [-0.0120079  -0.016528   -0.01394472]
 [-0.04545853 -0.01253827  0.00469703]
 [-0.01712634 -0.00461801  0.00479411]] 

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



None [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]], [[], [[]], [[], [[]]], [[], [[]], [[], [[]]]]]], [[], [[]], [[], [[]]], [[], [[]], [[]

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [162]:


loss = []
train_data = []
for step in range(100):
  a, b,c, d = sess.run([train,loss, w, b])
  loss.append(b)
  if step % 5 ==0 : 
    print(step, b, c ,d)
    train_data.append([c,d])

0 [] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



KeyboardInterrupt: ignored