In [1]:
print('LSTM Basics with TensorFlow')

LSTM Basics with TensorFlow


First create a tiny LSTM network to understand the architecture of LSTM ntetwork.

In [2]:
# import required libraries
import numpy as np 
import pandas as pd 
import tensorflow as tf

In [0]:
sess = tf.Session()

In [0]:
LSTM_CELL_SIZE = 4 # output size (dimenison), which is same as hidden size in the cell

A simple LSTM cell take three input ,
* previous_state 
* previous_output 
* current input

In [6]:
# Creating two tuple with a tensor os size [1,4] , one to give input as previous_state and one to give input as previous_output
state = (tf.zeros([1,LSTM_CELL_SIZE]),)*2
state

(<tf.Tensor 'zeros_1:0' shape=(1, 4) dtype=float32>,
 <tf.Tensor 'zeros_1:0' shape=(1, 4) dtype=float32>)

In [7]:
# Creating our first layer of LSTM

lstm_cell = tf.contrib.rnn.BasicLSTMCell(LSTM_CELL_SIZE, state_is_tuple=True)

Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.


In [8]:
lstm_cell

Creating some examples In this case batch_size = 1 and seq_len = 6

In [11]:
sample_input = np.array([[3,2,2,2,2,2]], dtype = 'float32')
sample_input

array([[3., 2., 2., 2., 2., 2.]], dtype=float32)

In [12]:
with tf.variable_scope('LSTM_sample1'):
  output, new_state = lstm_cell(sample_input, state)
sess.run(tf.global_variables_initializer())
print(sess.run(new_state))  

Instructions for updating:
Please use `layer.add_weight` method instead.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
LSTMStateTuple(c=array([[-0.8484598 , -0.6415175 , -0.21893793, -0.7073433 ]],
      dtype=float32), h=array([[-0.03540314, -0.5423226 , -0.12868975, -0.15458754]],
      dtype=float32))


In [13]:
print(sess.run(new_state)) 

LSTMStateTuple(c=array([[-0.8484598 , -0.6415175 , -0.21893793, -0.7073433 ]],
      dtype=float32), h=array([[-0.03540314, -0.5423226 , -0.12868975, -0.15458754]],
      dtype=float32))


In [14]:
print(sess.run(output))

[[-0.03540314 -0.5423226  -0.12868975 -0.15458754]]


So, we got result in the above case with a simple one layer LSTM cell

### Stacked LSTM

We will make more than one cell or layer of LSTM here.

In [0]:
cell =[]

In [0]:
LSTM_CELL_SIZE1 = 4 # number of hidden nodes


In [0]:
input_dim = 6 
sess1 = tf.Session()

In [0]:
cell1 = tf.contrib.rnn.BasicLSTMCell(LSTM_CELL_SIZE1)

In [19]:
cell1

In [0]:
cell.append(cell1)

In [0]:
LSTM_CELL_SIZE2 = 5 # 5 number of hidden nodes

In [22]:
cell2 = tf.contrib.rnn.LSTMCell(LSTM_CELL_SIZE2)

Instructions for updating:
This class is equivalent as tf.keras.layers.LSTMCell, and will be replaced by that in Tensorflow 2.0.


In [0]:
cell.append(cell2)

In [24]:
# Now define the stacked lstm
stacked_lstm = tf.contrib.rnn.MultiRNNCell(cell)

Instructions for updating:
This class is equivalent as tf.keras.layers.StackedRNNCells, and will be replaced by that in Tensorflow 2.0.


In [25]:
stacked_lstm

In [0]:
# Now we don't have data to input in the model, So we create placeholder

data = tf.placeholder(tf.float32, shape=[None, None, input_dim])

In [27]:
# Final layer
output, state = tf.nn.dynamic_rnn(stacked_lstm, data, dtype=tf.float32)

Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API


Lets say the input sequence length is 3, and the dimensionality of the inputs is 6. The input should be a Tensor of shape: [batch_size, max_time, dimension], in our case it would be (2, 3, 6)

In [28]:
#Batch size x time steps x features.
sample_input = [[[1,2,3,4,3,2], [1,2,1,1,1,2],[1,2,2,2,2,2]],[[1,2,3,4,3,2],[3,2,2,1,1,2],[0,0,0,0,3,2]]]
sample_input

[[[1, 2, 3, 4, 3, 2], [1, 2, 1, 1, 1, 2], [1, 2, 2, 2, 2, 2]],
 [[1, 2, 3, 4, 3, 2], [3, 2, 2, 1, 1, 2], [0, 0, 0, 0, 3, 2]]]

we can now send our input to network, and check the output:

In [0]:
sess.run(tf.global_variables_initializer())
r = sess.run(output, feed_dict={data: sample_input})

In [30]:
r

array([[[-0.00222789, -0.02565099, -0.00316924,  0.0219619 ,
          0.00994444],
        [-0.0085439 , -0.05156004, -0.02473292,  0.02793349,
          0.02557539],
        [-0.01832867, -0.06897813, -0.05684065,  0.01285889,
          0.04414111]],

       [[-0.00222789, -0.02565099, -0.00316924,  0.0219619 ,
          0.00994444],
        [ 0.00550237, -0.07309638, -0.00942218,  0.06529204,
          0.03650288],
        [ 0.00783434, -0.11582926, -0.04441761,  0.07752813,
          0.05473991]]], dtype=float32)

In [31]:
r.shape

(2, 3, 5)

As you see, the output is of shape (2, 3, 5), which corresponds to our 2 batches, 3 elements in our sequence, and the dimensionality of the output which is 5.

