In [0]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.15.0


# We are using 1.x version of Tensorflow

Building graph to create a variable

In [0]:
graph = tf.Graph()

In [0]:
with graph.as_default():
  a = tf.constant([2], name = 'constant_a')
  b = tf.constant([3], name ='constant_b')

In [8]:
a

<tf.Tensor 'constant_a_1:0' shape=(1,) dtype=int32>

building Session to get the output

In [11]:
sess = tf.Session(graph = graph)
result = sess.run(a)
print(result)

[2]


In [0]:
sess.close()

This way of initializing the session is not a good practice, as it consumes more of out time.

In [0]:
graph1 = tf.Graph()

In [0]:
with graph1.as_default():
  a = tf.constant([3], name='a')
  b = tf.constant([4], name='b')
  c = a + b


In [18]:
with tf.Session(graph = graph1) as sess :
  result = sess.run(c)
  print(result)

[7]


In [0]:
with graph1.as_default():
  a = tf.constant(1)
  b = tf.constant([2])
  c = tf.constant([2,3,4])
  d = tf.constant([[1,2,3,4],[2,3,4,5],[5,6,6,7]])
  e = tf.constant([ [[1,2,3],[4,5,6],[7,8,9]],
                   [[11,22,33],[44,55,66],[77,88,99]],
                   [[111,222,333],[444,555,666],[777,888,999]]])

Now build the session to run the graph

In [27]:
with tf.Session(graph = graph1) as sess:
  result = sess.run(a)
  print(result)
  b = sess.run(b)
  print(b)
  c = sess.run(c)
  print(c)
  d = sess.run(d)
  print(d)
  e = sess.run(e)
  print("")
  print(e)

1
[2]
[2 3 4]
[[1 2 3 4]
 [2 3 4 5]
 [5 6 6 7]]

[[[  1   2   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]

 [[111 222 333]
  [444 555 666]
  [777 888 999]]]


Defining a variable

In [0]:
v = tf.Variable(0)

Variables must be initialized by running an initialization operation after having launched the graph. We first have to add the initialization operation to the graph:

In [0]:
init_op = tf.global_variables_initializer()

In [0]:
update = tf.assign(v, v+1)

In [31]:
with tf.Session() as sess:
  sess.run(init_op)
  print(sess.run(v))
  for _ in range(3):
    sess.run(update)
    print(sess.run(v))

0
1
2
3


Placeholders

In [35]:
a = tf.placeholder(tf.float32)
b = a *a
with tf.Session() as sess:
  r = sess.run(b, feed_dict={a : 2})
  print(r)

4.0


Operations in TensorFlow

In [0]:
tf.matmul()
tf.add()
tf.constant
tf.nn.sigmoid